name: Setup Files

on:
  workflow_dispatch:

concurrency:
  group: setup-files-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
